workflows:
  ios-native-build:
    name: Project Nova iOS Build (IPA Only)

    # mac hardware
    instance_type: mac_mini_m1

    # environment
    environment:
      xcode: latest
      vars:
        # FIX: Changed path to point to the .xcworkspace file, which is MANDATORY after 'pod install'.
        XCODE_PROJECT_NAME: "ProjectNova/ProjectNova.xcworkspace"
        XCODE_SCHEME: "ProjectNova"

    # build steps
    scripts:
      # 1. Install CocoaPods (Crucial: runs successfully, creating the .xcworkspace file)
      - name: Install CocoaPods
        script: |
          if [ -f ProjectNova/Podfile ]; then
            echo "Podfile found. Installing dependencies."
            cd ProjectNova
            pod install
            cd ..
          else
            echo "No Podfile found. Skipping pod install."
          fi

      # 2. Set up code signing
      - name: Set up code signing
        script: |
          # This tool is smart enough to use the workspace path to deduce the project.
          app-store-connect fetch-signing-files "$XCODE_PROJECT_NAME" \
            --platform IOS \
            --type IOS_APP_STORE \
            --create
          xcode-project use-profiles

      # 3. Run unit tests (optional)
      - name: Run Unit Tests
        script: |
          # FIX: Must use the -workspace flag when building with an .xcworkspace file.
          xcodebuild test -workspace "$XCODE_PROJECT_NAME" -scheme "$XCODE_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 14'

      # 4. Build IPA
      - name: Build IPA
        script: |
          # FIX: Must use the --workspace flag for xcode-project build-ipa.
          xcode-project build-ipa \
            --workspace "$XCODE_PROJECT_NAME" \
            --scheme "$XCODE_SCHEME"

    # artifacts (IPA will be downloadable)
    artifacts:
      - build/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - $CM_BUILD_DIR/export_options.plist